/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ragnalara' at '11/2/15 6:58 PM' with Gradle 2.8
 *
 * @author ragnalara, @date 11/2/15 6:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
